Add comment on international domain names
w3c-ccg/did-method-web pull request #76
Opened 2023-03-31 02:08 UTC by OR13

2023-03-31 16:03 UTC, TallTed requested changes
Picking nits...

2023-03-31 16:03 UTC, TallTed commented on index.html
> +          allow unicode in method name or method specific identifiers.
```suggestion
          allow Unicode in method name nor method specific identifiers.
```

2023-03-31 16:03 UTC, TallTed commented on index.html
> +          or path components that contain unicode characters.
```suggestion
          or path components that contain Unicode characters.
```

2023-04-25 19:10 UTC, dmitrizagidulin approved these changes
👍 
Thanks @OR13!

2023-04-26 11:51 UTC, TallTed approved these changes

2023-05-06 16:33 UTC, merged